FROM python:3.10.0

WORKDIR /usr/src/app

COPY . .

RUN pip install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

RUN chmod a+x ./*.py

ENTRYPOINT ["python", "-u", "./main.py" ]